<?php include("inc/header.php"); ?>

        <div class="container">
            <div class="row namer text-center">
                <h5>Margot Jones</h5>
                <h1>Personal Chef</h1>
            </div>
        </div>

        <div class="container main-about">
            <img src="img/pic4.jpg" alt="..." height="800px" width="100%">
            <p class="para-1">Nullam sem quam, malesuada sit amet vulputate id, pulvinar id ante. Nulla pulvinar iaculis sapien, nec tincidunt enim tempor nec. Sed nec auctor dui, sed luctus nibh. Donec vel mattis libero. Suspendisse dignissim metus quis velit sagittis, eget dictum velit posuere. Aliquam aliquam nisl et lectus tincidunt interdum. Vivamus feugiat nisi leo, sit amet sagittis leo cursus et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur vel dapibus urna. Vivamus eget urna enim. Quisque ut efficitur mauris. Aliquam ut rutrum lorem. Sed vitae consectetur massa, iaculis dapibus nisl. Aenean lobortis ultrices eros vulputate maximus.</p>
            <img src="img/pic5.jpg" alt="..." height="800px" width="100%">
            <h1 style="color:red">Background</h1>
            <p class="para-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique scelerisque nisi, eget feugiat velit imperdiet non. Donec a augue leo. Donec ut metus sed elit tincidunt pharetra. Morbi id hendrerit tellus, ac varius dolor. Vestibulum sodales quis est at iaculis. Aenean interdum faucibus nisi. Fusce mi neque, dictum a elementum vel, vulputate vitae magna. Quisque venenatis ipsum non nulla malesuada, at cursus quam pellentesque. Integer bibendum est quis nunc luctus, vel aliquet est ultricies. Cras placerat convallis metus sit amet mattis. Etiam accumsan malesuada est tincidunt rutrum.</p>
            <p class="para-2">Etiam sit amet tincidunt tortor, id posuere quam. Nunc volutpat mollis arcu feugiat tristique. Praesent ipsum dui, vestibulum non ipsum at, porta eleifend dui. Donec malesuada orci vel lorem convallis, non congue diam ultricies. Donec eget purus a velit vulputate vulputate. Duis facilisis sodales accumsan. Proin in tempus magna. Vestibulum dignissim at orci at tristique. Sed lobortis luctus turpis, et finibus orci scelerisque in. Pellentesque a laoreet enim. Fusce eleifend molestie pretium. Pellentesque blandit, mauris nec tempus gravida, leo eros fringilla est, id commodo velit ex nec urna. Aenean maximus mi in augue aliquet consectetur. Donec auctor nisi a ex pulvinar venenatis.</p>
            <p class="para-2">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque congue orci sit amet suscipit laoreet. Aenean vitae lorem rhoncus, semper est quis, blandit nibh. Donec iaculis purus ex. Quisque mattis nibh quis risus efficitur mollis. Nullam nisi libero, pretium quis lacus a, sodales rutrum augue. Mauris eu maximus lectus. Aenean pharetra nibh quis nisl commodo, vitae dictum mauris eleifend. Ut et mauris eget ligula venenatis ornare a eget ipsum. Sed a ipsum semper, facilisis nunc vitae, vestibulum massa. Nunc sit amet imperdiet justo. Ut sagittis accumsan lacus nec auctor. Curabitur et rutrum orci. Duis dapibus pulvinar erat, quis elementum dui.</p>
            <p class="para-2">Nullam sem quam, malesuada sit amet vulputate id, pulvinar id ante. Nulla pulvinar iaculis sapien, nec tincidunt enim tempor nec. Sed nec auctor dui, sed luctus nibh. Donec vel mattis libero. Suspendisse dignissim metus quis velit sagittis, eget dictum velit posuere. Aliquam aliquam nisl et lectus tincidunt interdum. Vivamus feugiat nisi leo, sit amet sagittis leo cursus et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur vel dapibus urna. Vivamus eget urna enim. Quisque ut efficitur mauris. Aliquam ut rutrum lorem. Sed vitae consectetur massa, iaculis dapibus nisl. Aenean lobortis ultrices eros vulputate maximus.</p>
            <p class="para-2">Pellentesque eget vehicula ex. Vestibulum non porta nisl. Nam viverra ornare urna in facilisis. Morbi lacus elit, iaculis sed urna sed, aliquet ultrices massa. Nam sit amet turpis sit amet mi cursus ullamcorper sed in lectus. In congue, sapien nec tincidunt rutrum, purus tortor aliquam lorem, nec posuere dui lacus non ipsum. Mauris sapien ligula, rhoncus sit amet viverra semper, ornare nec lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras posuere ultrices orci, ac aliquam tortor lobortis ultricies.</p>
        </div>
<?php include("inc/footer.php"); ?>